### ISSUE TITLE
When it comes to JS frameworks, which do you think a new developer should start with. Angular, Backbone or React. And why that one?

### ISSUE THREAD

**Issue by Rchristiani** [mxriverlynn/ama#10]

**Comment by mxriverlynn** [comment]
I don't think there's a correct answer to this question without considering further context of the person's situation. some of this depends on whether or not you mean true "beginner" - never written code before / still struggling with basic syntax - or relatively inexperienced programmer that has written code but not javascript. 

most people are interested in "getting things done" when they are first learning, so I would steer clear of javascript frameworks entirely. start with some of the many great code "school" lessons that teach in simple and clear instructions, with instant visual output. 

if we're talking about people that are already familiar with javascript, html and css, then you're probably looking at people who have friends or coworkers in this space. get the tutoring and one-on-one training in the framework of the friend's choice. you'll get better results, faster, that way.

but really, there's no one right way or right answer to this.
