### ISSUE TITLE
What do you think about CoffeeScript in the future?

### ISSUE THREAD

**Issue by linus-amg** [mxriverlynn/ama#11]

**Comment by linus-amg** [comment]
in connection with a development stack of browserify, jquery/sprint, underscore, backbone, marionette for the front-end and express/mongoose backend (also coffeescript)

**Comment by mxriverlynn** [comment]
I've spent enough time dealing with coffeescript to know that i don't personally like it...

but, i think coffeescript played an important role in moving JavaScript forward. features like destructuring assignment and list comprehensions were directly influenced by coffeescript (which took these from ruby / python / etc). 

given that, i think coffeescript can still have an important role in the future of web development.  coffeescript is showing us new and better ways to accomplish things and babel.js is showing us how to do the "next" version of JavaScript.

still, i cringe when i see open source projects written in coffeescript and usually ignore them. i just don't like it. it claims to be "just javascript" - but that's a lie. if it was just javascript, then it wouldn't be coffeescript. coffeescript adds more complexitity than necessary, and convolutes already confusing ideas like "this" (using @ and -> vs =>).
