### ISSUE TITLE
Most influential JS book 

### ISSUE THREAD

**Issue by jdaudier** [mxriverlynn/ama#13]
What are some of your favorite or most influential JS book(s) :book:  that has helped you grow the most as a developer?

**Comment by mxriverlynn** [comment]
easily the [JavaScript Patterns](http://www.amazon.com/JavaScript-Patterns-Stoyan-Stefanov/dp/0596806752/ref=sr_1_1?ie=UTF8&qid=1439324613&sr=8-1&keywords=javascript+patterns) book by Stoyan Stefanov

it's a bit dated now, with ES6 stuff... but this book is what took me from amateur to pro with the core of javascript.

from there, pretty much everything by Nicholas Zakas and Axel Rauschmeyer

**Comment by jdaudier** [comment]
Thanks!
