### ISSUE TITLE
What tools do you use on a daily basis?

### ISSUE THREAD

**Issue by arthurvr** [mxriverlynn/ama#17]

**Comment by mxriverlynn** [comment]
most of what i use daily is shown in [this video on building a development workflow](http://derickbailey.com/2014/11/17/building-a-bada55-node-dev-env/), and this video on [ES6 in browser apps](http://derickbailey.com/2015/08/31/building-es6-browser-apps-w-babel-and-grunt/)
- vim
- git
- nodejs
- grunt
- jshint
- browserify
- babel
- livereload
- nodemon

and various other bits shown in these videos

**Comment by dmitriz** [comment]
No gulp?
