### ISSUE TITLE
What are your top 5 scotches?

### ISSUE THREAD

**Issue by jcarouth** [mxriverlynn/ama#18]

**Comment by mxriverlynn** [comment]
that's a tough one... so many good ones out there!

only listing scotch... 

by distiller:

1) Lagavulin
1) Balvenie
3) Oban
4) Laphroaig
5) Ardbeg

notice that 4 / 5 are Isla scotches... love that smokey peaty drinking a pile of dirt taste. :D

if i can list single-malt whiskeys, not just scotch, i'll add in Balcones Single Malt and the various Japanese Single Malts (Yamazaki, for example)

Listing by specific bottles that i've purchased (no specific order):
- Lagavulin 16yr
- Lagavulin Distiller's Edition
- Balvenie 17yr Peated Cask
- literally any Balvenie bottle (12yr, 14yr rum cask, 15yr, 17yr ... tempted to buy a 21 yr)
- Oban Little Bay
- Oban 14 yr
- Laphroaig 18
- Laphroaig quarter cask
- Ardbeg 12 (want to buy an Uigeadail)
- Coal Ila 12
- Yamazaki 12

non-scotch whiskeys
- Balcones Single Malt (local waco)
- Any other Balcones (Baby Blue, True Blue, Brimstone, Rumble, etc)
- Garrison Brothers bourbon
- Willet Reserve bourbon
