### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [mxriverlynn/ama#19]

**Comment by mxriverlynn** [comment]
In the past, I have done this a lot. Whether it was at full-time jobs w/ team members and coworkers, or as a consultant that would come in to a company to help get the team up to speed on a technology, this was a large part of my job. 

More recently, I haven't had time to engage in this directly... my screencasts at WatchMeCode.net and my blogging at DerickBailey.com somewhat take the place of this, but I realize that there is a huge difference between generalized information in this format vs one-on-one mentoring.

I would like to get back in to a more formal mentoring role at some time. It's always a question of time, though...
