### ISSUE TITLE
How do you create your screencasts?

### ISSUE THREAD

**Issue by Faarr** [mxriverlynn/ama#23]
I'm thinking about recording my own screencast (don't worry - no about JS) and I'm very interested in your process. Could you describe it with more details? 
- Do you write script first? 
- What software and hardware do you use?
- How did you create your intro?

Thanks in advance!

regards

**Comment by mxriverlynn** [comment]
## The short answers:

> Do you write script first?

Nope! I practice once or twice, hit record and go.

> What software and hardware do you use?

I'm on a Mac, and I use Screenflow to record and edit. Highly recommended if you're on a mac. 

I also use a Rode Podcaster mic and a Logitech c920 camera.

> How did you create your intro?

I use Apple Motion 5 for this. the most recent version was created by someone else, via upwork.com contract

## The long answers:

> Do you write script first?

I've done this in the past, and it doesn't work well for me. It adds a lot of extra time for little to no benefit, in my experience.

It would take several hours of writing and editing to create a script that would follow the content of the code. 

Then recording the audio separately would require me to edit the audio and video together, splitting things apart and moving content around too much. 

The end result in my early screencasts is less than ideal - it sounds scripted, and monotone. There's no real personality in it.

At this point, I make mental notes about the points that I need to cover while I'm practicing the code once or twice. 

Having a general outline in my head is enough for me. Not having it all scripted allows it to be more natural, like a conversation.

Ultimately, that's what I want - a conversation with the person watching. I imagine the mic and camera as another person sitting there, listening and I talk to that "person" as if we're in a one-on-one conversation.

If you're not already used to sitting in front of a mic and camera, take some time to practice recording. This is going to be critical early on, to creating a natural flow.

For some people, thinking of this like doing a presentation in front of a group will help them get into the right mind set.

For me, I prefer the more personal, one-on-one conversation. 

Try some different ideas. Think about the screencasts and presentations you've seen, where you really enjoyed listening to the person speaking, and then copy their style as much as you can. From there, you'll start to develop your own style.

lastly - don't be afraid to publish something that you think is terrible.

if you look at my earliest videos on watchmecode, they're awful by my current standards. but people loved them anyways. It's more important to produce than to perfect. you can save perfection for later, and you will naturally improve with each recording you do.

> What software and hardware do you use?

Screenflow is pretty darn amazing these days. It covers everything I need for screencasts, including audio processing, filters and effects. There are a few things that are less than ideal, but for the cost, you can't beat it.

If you're on windows, Camtasia is popular, but very expensive and tends to be buggy / difficult to use.

There are much more powerful tools out there from Sony, Adobe and Apple. But really, any recording and editing software should work.

The key is not to get "the right" software, but to learn the software you choose and take full advantage of the features it offers. 

The mic is probably the most important part of recording. If you can only spend $ on one thing, it should be this.

The industry standard i the Rode Podcaster. It's a broadcast quality mic that plugs in via USB. It's a great mic, with great sound, and very versatile. You'll need a mic stand (swing arm, with shock mount) for it, though. It can get expensive.

if you prefer a mic that sits on your desk, no so close to you, go with the Blue Yeti. It's the second most popular mic in our industry. it will pick up sound from all over the room, though. 

> How did you create your intro?

any tool that can create an animation will work.

it could be PowerPoint or another slide deck app - and i've done that in the past. 

motion graphics are great, but can be time consuming to create, expensive to buy, and can add a lot of effort to your production when you should be focused on getting the content created and released. 

don't spend a lot of time or money on this, at first. get your screencasts recorded, edited and published. you can add these kinds of details to later screencasts, and you can always go back and re-edit the old episodes to add this stuff.

...

hope that helps! and let me know if you have anymore questions :)
- Derick

**Comment by Faarr** [comment]
Hi Derick,

thank you very much for the detailed answer. Especially the long part gave me lots of value.

I want to record it on Windows, but Camtasia is out of my budget for now. Also I don't want to invest so much $ in mic, if I'm not sure if I do screencast for real. For now I will go with some cheaper alternatives. Later (if I continue doing screencasts) I will bought more professional equipment.

I have additional (technical) question. On your page people can download videos you've created. What video codec do you use to mitigate problem with video codec license?

Thanks!

**Comment by mxriverlynn** [comment]
i completely understand budget constraints! 

the most important part about recording your voice, is to have a microphone of some kind, other than the built-in laptop mic. even if you buy a $30 "chat" headset, the mic on that will be better than talking at the mic on your laptop. 

at $50, the Blue "Snowball" mic is also a good option for less $.

regarding the video codec, i use .mp4 with h.264 video and aac audio encoding, with these settings:

![image](https://cloud.githubusercontent.com/assets/75190/18884058/712ddfb4-84ab-11e6-9be7-e0e3bfe5a6bf.png)

this format / encoding is supported by all the major browsers and mobile devices, these days. i haven't yet had anyone complain that they can't play my screencasts on their device, at least.

**Comment by Faarr** [comment]
Probably I will go with some cheaper mic - thanks for pointing Blue "Snowball" - looks like good option for starting with.

About codes I was more interested in licensing fees, but reading this thread: http://video.stackexchange.com/questions/14694/mp4-h-264-patent-issues/14699 
I come to conclusion that it's case only for "big" publishers.

I'm really thankful for  help! 

Taking this opportunity I want to say that you do great job with your videos and blog/articles. Thanks!
