### ISSUE TITLE
Does Backbone.js have a future in your opinion?

### ISSUE THREAD

**Issue by sindresorhus** [mxriverlynn/ama#4]

**Comment by mxriverlynn** [comment]
as much of a future as any current library / framework!

there's always room for the DIY-architecture libraries, and Backbone fits this space well. there are enough add-ons and plugins to create nearly any framework or architecture that you want with it, while still keeping the core of it "backbone"-like. 

backbone remains a popular choice for its flexibility, and a lot of companies still depend on it every day. the elusive "complete rewrite" tends to keep tools like this around for a long time, and the backbone community doesn't seem to be slowing down much. 

so, yeah... i still think there's a good future for backbone. it won't outlive something newer / better, but nothing ever does in technology.
