### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [mxriverlynn/ama#5]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by mxriverlynn** [comment]
### editor / themese / fonts

vim (macvim) with a handful of plugins for git status, language syntax highlighting, bufexplorer, nerdtree, etc. nothing huge or anything, though. most of the work i do is through grunt / other built tools

i use monaco font, size 20 right now. probably going to bump that up soon. i'm old. :P

dark theme... twilight color scheme. soft colors, but all distinct and easy to identify. 

### terminal

basic terminal built in to osx. i use a lot of tabs for separate processes on projects, and often save a group of pre-configured tabs as a window group to make it easier to start up a project

### general process

i do most of my work in node.js these days... haven't yet bought in to the io.js release cycles, so i've kind of avoided that.

i automate the crap out of everythign in grunt. gulp looks weird to me and i don't really care about which build tool someone uses, as long as they automate repeating processes

i run browserify modules, am doing a lot of ES6 stuff lately, and still build backbone/marionette apps for front-end code with express on the back-end. 

i build very component-oriented browser apps. a typical screen will have 10 components or more, each with their own "controller" (mediator pattern) to make the logic and flow separate from the UI / view layer. i'm a big fan of component style development, where things plug in to each other quickly and easily. it's simple to do this with backbone and creates much cleaner code... probably getting close to emberjs style, but i haven't yet made that jump

on the back-end, any long-running process or code that doesn't need to happen during the lifecycle of an HTTP request handler goes through rabbitmq and is processed in the background somewhere else

you can see my setup and workflow from a year ago, in this presentation i did at nodevember 2014: http://derickbailey.com/2014/11/17/building-a-bada55-node-dev-env/ - youtube video included in there
