### ISSUE TITLE
What excites you most about the future of the web?

### ISSUE THREAD

**Issue by sindresorhus** [mxriverlynn/ama#7]

**Comment by mxriverlynn** [comment]
it was going to be webcomponents... but those are looking like a dead-end at this point. with no browsers really supporting them without something like polymer, it's hard to say if they have a future yet. 

but i think component based UI architectures, and good architecture in general, are really exciting right now. 

there are plenty of JS dev communities that are moving forward with these ideas, including backbone, angular, ember, etc. the more i see this happening, the happier it makes me. all the best parts of what i learned in "enterprise" application development and architecture are finally showing up in the best JS frameworks... only we have better tooling to go with it, and a better runtime (IMO)! 

still looking for some kind of web components like thing... but the current direction is good.
