### ISSUE TITLE
What is your strongest personal quality?

### ISSUE THREAD

**Issue by sindresorhus** [mxriverlynn/ama#8]

**Comment by mxriverlynn** [comment]
hmmmmmm...

I'll assume "quality" means a positive thing in this case... cause I have a lot of strong, negative things in my character.

probably my ability to think and visualize things in relationships to each other. from code, to hardware, maps and ingredients for food, I think in spacial relationships. 

with code, if something doesn't visualize in clear relationships in my head, then I either have a misunderstanding our something in the design is wrong.

if I could pick a second thing, it would be teaching through example by breaking things down based on the relationships I see. I think my screencasts, books and blog posts reflect this pretty well. hopefully others agree :)
