### ISSUE TITLE
Which is your favorite pokemon?

### ISSUE THREAD

**Issue by sindresorhus** [mxriverlynn/ama#9]

**Comment by mxriverlynn** [comment]
lol, none.

except maybe @tazsingh's "charzard" bmw :)

 I'm more a fan of care bears. definitely grumpy bear. I have plans on getting a grumpy bear tattoo at some point. just hasn't happened yet!

**Comment by tazsingh** [comment]
Aw thanks @derickbailey :)

Obligatory photo:
![](https://igcdn-photos-d-a.akamaihd.net/hphotos-ak-xaf1/t51.2885-15/10488744_674407129279699_1156927633_n.jpg)
